export const TRUMPS = [
    {
        id: 1,
        value: 2,
        texture: "/textures/trump/1.webp",
        name: "Двойка",
        desc: "Даёт карту 2 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 2,
        value: 3,
        texture: "/textures/trump/2.webp",
        name: "Тройка",
        desc: "Даёт карту 3 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 3,
        value: 4,
        texture: "/textures/trump/3.webp",
        name: "Четвёрка",
        desc: "Даёт карту 4 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 4,
        value: 5,
        texture: "/textures/trump/4.webp",
        name: "Пятёрка",
        desc: "Даёт карту 5 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 5,
        value: 6,
        texture: "/textures/trump/5.webp",
        name: "Шестёрка",
        desc: "Даёт карту 6 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 6,
        value: 7,
        texture: "/textures/trump/6.webp",
        name: "Семёрка",
        desc: "Даёт карту 7 в начале раунда, если её нет ни у вас, ни у оппонента",
    },
    {
        id: 7,
        texture: "/textures/trump/7.webp",
        name: "Bless",
        desc: "В случае если после раунда расстояние между вами и Мистером Пилой должна быть равна 0, то Мистер Пила останется на том же месте где и был и вы не умрёте.",
        chance: 1.67,
    },
    {
        id: 8,
        texture: "/textures/trump/8.webp",
        name: "Bloodshed",
        desc: "Уничтожает козырь на столе вашего оппонента и повышает ставку на один.",
        chance: 4.17,
    },
    {
        id: 9,
        texture: "/textures/trump/9.webp",
        name: "Destroy",
        desc: "Уничтожает козырь на столе вашего оппонента.",
        chance: 4.17,
    },
    {
        id: 10,
        texture: "/textures/trump/10.webp",
        name: "Disservice",
        desc: "Ваш оппонент получает одну карту.",
        chance: 2.5,
    },
    {
        id: 11,
        texture: "/textures/trump/11.webp",
        name: "Exchange",
        desc: "Меняет последнюю карту у вас и вашего оппонента друг на друга, если у обоих или у кого-то одного только одна карта, то ничего не произойдёт.",
        chance: 4.17,
    },
    {
        id: 12,
        texture: "/textures/trump/12.webp",
        name: "Friendship",
        desc: "Выдаёт вам и вашему оппоненту по 2 козыря.",
        chance: 4.17,
    },
    {
        id: 13,
        texture: "/textures/trump/Image14.webp",
        name: "Go for 17",
        desc: "Понижает количество необходимых очков для победы до 17.",
        chance: 4.17,
    },
    {
        id: 14,
        texture: "/textures/trump/Image15.webp",
        name: "Go for 24",
        desc: "Повышает количество необходимых очков для победы до 24.",
        chance: 4.17,
    },
    {
        id: 15,
        texture: "/textures/trump/Image16.webp",
        name: "Go for 27",
        desc: "Повышает количество необходимых очков для победы до 27.",
        chance: 4.17,
    },
    {
        id: 16,
        texture: "/textures/trump/Image17.webp",
        name: "Hush",
        desc: "Выдаёт вам карту рубашкой вверх.",
        chance: 4.17,
    },
    {
        id: 17,
        texture: "/textures/trump/Image18.webp",
        name: "One-up",
        desc: "Повышает ставку на 1.",
        chance: 4.17,
    },
    {
        id: 18,
        texture: "/textures/trump/Image27.webp",
        name: "Two-up",
        desc: "Повышает ставку на 2.",
        chance: 4.17,
    },
    {
        id: 19,
        texture: "/textures/trump/Image25.webp",
        name: "Shield",
        desc: "Понижает ставку на 1.",
        chance: 4.17,
    },
    {
        id: 20,
        texture: "/textures/trump/Image26.webp",
        name: "Shield+",
        desc: "Понижает ставку на 2.",
        chance: 4.17,
    },
    {
        id: 21,
        texture: "/textures/trump/Image23.webp",
        name: "Remove",
        desc: "Удаляет последнюю карту вашего оппонента. Если у оппонента только одна карта, ничего не происходит.",
        chance: 4.17,
    },
    {
        id: 22,
        texture: "/textures/trump/Image24.webp",
        name: "Return",
        desc: "Удаляет последнюю вашу карту. Если у вас осталась только одна карта, ничего не происходит.",
        chance: 4.17,
    },
    {
        id: 23,
        texture: "/textures/trump/Image19.webp",
        name: "Perfect Draw",
        desc: "Выдаёт самую лучшую карту при условии что её нет ни у вас, ни у вашего оппонента, иначе ничего не произойдёт.",
        chance: 4.17,
    },
    {
        id: 24,
        texture: "/textures/trump/Image20.webp",
        name: "Refresh",
        desc: "Убирает все ваши карты и даёт две новых.",
        chance: 4.17,
    },
    {
        id: 25,
        texture: "/textures/trump/Image22.webp",
        name: "Reincarnation",
        desc: "Уничтожает козырь на столе вашего оппонента и выдаёт вам рандомный козырь.",
        chance: 4.17,
    },
]

export function getRandomTrumps(count = 3) {
    return Array.from({ length: count }, () =>
        TRUMPS[Math.floor(Math.random() * TRUMPS.length)]
    )
}
